<?php
/** @var $block \Magento\Checkout\Block\Cart\Sidebar */
?>

<div data-block="minicart" class="minicart-wrapper">
	<div class="cart-first">
		<div class="header-minicart-title"><span>Mijn wijnmandje</span></div>
		<a class="action showcart" href="<?php /* @escapeNotVerified */ echo $block->getShoppingCartUrl(); ?>"
		   data-bind="scope: 'minicart_content'">
			<span class="text"><?php /* @escapeNotVerified */ echo __('My Cart'); ?></span>
		</a>
	</div>
	<div class="cart-second">
		<span class="title">Aantal</span>
		<a class="action showcart" href="<?php /* @escapeNotVerified */ echo $block->getShoppingCartUrl(); ?>"
		   data-bind="scope: 'minicart_content'">
			<span class="text"><?php /* @escapeNotVerified */ echo __('My Cart'); ?></span>
				<span class="counter qty empty"
				  data-bind="css: { empty: !!getCartParam('summary_count') == false }, blockLoader: isLoading">
				<span class="counter-number"></span>
				<span class="counter-label">
				<!-- ko if: getCartParam('summary_count') -->
					<!-- ko text: getCartParam('summary_count') --><!-- /ko -->
					<!-- ko i18n: 'items' --><!-- /ko -->
				<!-- /ko -->
				<!-- ko ifnot: getCartParam('summary_count') -->
					<!-- ko text: 0 --><!-- /ko -->
				<!-- /ko -->
				</span>
			</span>
		</a>
		<span class="totalprice">
			<div class="subtotal" data-bind="scope: 'minicart_content'">
				<span data-bind="html: getCartParam('subtotal')"></span> 
			</div>
        </span>
	</div>
	<div class="cart-third">
		<span class="title">Totaal</span>
		<span class="totalprice">
			<div class="subtotal" data-bind="scope: 'minicart_content'">
				<span data-bind="html: getCartParam('subtotal')"></span> 
			</div>
		</span>
	</div>
	<div class="cart-fourth">
		<a href="/checkout/"><div class="block"><span class="title">Afrekenen</span><span class="arrow">></span></div></a>
	</div>
    <?php if ($block->getIsNeedToDisplaySideBar()): ?>
        <div class="block block-minicart empty"
             data-role="dropdownDialog"
             data-mage-init='{"dropdownDialog":{
                "appendTo":"[data-block=minicart]",
                "triggerTarget":".showcart",
                "timeout": "2000",
                "closeOnMouseLeave": false,
                "closeOnEscape": true,
                "triggerClass":"active",
                "parentClass":"active",
                "buttons":[]}}'>
            <div id="minicart-content-wrapper" data-bind="scope: 'minicart_content'">
                <!-- ko template: getTemplate() --><!-- /ko -->
            </div>
            <?php echo $block->getChildHtml('minicart.addons'); ?>
        </div>
    <?php endif ?>
    <script>
        window.checkout = <?php /* @escapeNotVerified */ echo \Zend_Json::encode($block->getConfig()); ?>;
    </script>
    <script type="text/x-magento-init">
    {
        "[data-block='minicart']": {
            "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>
        },
        "*": {
            "Magento_Ui/js/block-loader": "<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/loader-1.gif'); ?>"
        }
    }
    </script>
</div>


