<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$posts = $objectManager->create('\FishPig\WordPress\Model\ResourceModel\Post\Collection')
	->addPostTypeFilter('post')
	->setOrderByPostDate()
	->addIsViewableFilter()
	->setPageSize(3)
	->load();
?>
<?php if (count($posts) > 0): ?>
	<ul>
		<?php foreach($posts as $post): ?>
			<li>
                            <div class="post-icon">
				<?php if ($image = $post->getFeaturedImage()): ?>
					<a href="<?php echo $post->getUrl() ?>">
                                            <img src="<?php echo $image->getAvailableImage() ?>" src="<?php echo $this->escapeHtml($post->getPostTitle()) ?>" width="50" height="50" />
					</a>
				<?php endif; ?>
                            </div>
                            <a class="linl-pos-ffoter" href="<?php echo $post->getUrl() ?>"><?php echo $this->escapeHtml($post->getPostTitle()) ?></a>
                            <small class="post-date">
                                <?php echo $post->getPostDate(); ?>
                                           </small>
				
		<?php endforeach; ?>
	</ul>
<?php endif; ?>