<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="col-md-12">
                        <div class="row">
                            <div class="col-md-6 col-md-offset-3">
                                <div class="innerPage-Title text-center">
                                    <h4><?php /* @escapeNotVerified */ echo __('SHOPPING BAG') ?></h4>
                                </div>
                            </div>
                        </div>
                    </div>
<div class="col-md-12">
 <ul class="opc-progress-bar new">
        <li class="opc-progress-bar-item _active">
            <span>Shopping Bag</span>
        </li>
        <li class="opc-progress-bar-item">
            <span>Shipping Detail</span>
        </li>
        <li class="opc-progress-bar-item">
            <span>Billing & Payment Details</span>
        </li>
        <li class="opc-progress-bar-item">
            <span>Order Confirmation</span>
        </li>
    </ul>
 </div>