<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**  @var $block \Magento\Checkout\Block\Cart */


$item_count = count( $block->getItems() );
?>
<?php $mergedCells = ( $this->helper( 'Magento\Tax\Helper\Data' )->displayCartBothPrices() ? 2 : 1 ); ?>
<?php echo $block->getChildHtml( 'form_before' ) ?>
<form action="<?php /* @escapeNotVerified */
echo $block->getUrl( 'checkout/cart/updatePost' ) ?>"
      method="post"
      id="form-validate"
      data-mage-init='{"validation":{}}'
      class="form form-cart">
	<?php echo $block->getBlockHtml( 'formkey' ); ?>
    <div class="cart table-wrapper<?php echo $mergedCells == 2 ? ' detailed' : ''; ?>">
        <table id="shopping-cart-table"
               class="cart items data table table-hover table-striped"
               data-mage-init='{"shoppingCart":{"emptyCartButton": "action.clear",
               "updateCartActionContainer": "#update_cart_action_container"}}'>

            <thead>
            <tr>
                <th class="col item" scope="col" colspan="7">
                    <h5 class="text-primary"><strong><?php echo $item_count; ?></strong> <?php echo $item_count > 1 ? "ITEMS" : "ITEM"; ?> IN YOUR BAG
                    </h5>
                </th>

                <!--                <th class="col item" scope="col"><h5 class="text-primary">--><?php ///* @escapeNotVerified */
				//						echo __( 'ITEM' ) ?><!--</h5></th>-->
                <!--                <th class="col desc" scope="col"><h5 class="text-primary">--><?php ///* @escapeNotVerified */
				//						echo __( 'DESCRIPTION' ) ?><!--</h5></th>-->
                <!--                <th class="col color" scope="col"><h5 class="text-primary">--><?php ///* @escapeNotVerified */
				//						echo __( 'COLOR' ) ?><!--</h5></th>-->
                <!--                <th class="col size" scope="col"><h5 class="text-primary">--><?php ///* @escapeNotVerified */
				//						echo __( 'SIZE' ) ?><!--</h5></th>-->
                <!--                <th class="col qty" scope="col"><h5 class="text-primary">--><?php ///* @escapeNotVerified */
				//						echo __( 'QTY' ) ?><!--</h5></th>-->
                <!--                <th class="col price" scope="col"><h5 class="text-primary">--><?php ///* @escapeNotVerified */
				//						echo __( 'UNIT PRICE' ) ?><!--</h5></th>-->
                <!--                <th class="col subtotal" scope="col"><h5 class="text-primary">--><?php ///* @escapeNotVerified */
				//						echo __( 'ITEM TOTAL' ) ?><!--</h5></th>-->
            </tr>

            </thead>
			<?php foreach ( $block->getItems() as $_item ): ?>
				<?php echo $block->getItemHtml( $_item ) ?>
			<?php endforeach ?>
        </table>
    </div>
    <div class="cart main actions">
        <!--
        <?php //if ($block->getContinueShoppingUrl()): ?>
            <a class="action continue"
               href="<?php //echo $block->escapeUrl($block->getContinueShoppingUrl()) ?>"
               title="<?php //echo $block->escapeHtml(__('Continue Shopping')); ?>">
                <span><?php /* @escapeNotVerified */ //echo __('Continue Shopping') ?></span>
            </a>
        <?php //endif; ?>

        <button type="submit"
                name="update_cart_action"
                data-cart-empty=""
                value="empty_cart"
                title="<?php //echo $block->escapeHtml(__('Clear Shopping Cart')); ?>"
                class="action clear" id="empty_cart_button">
            <span><?php /* @escapeNotVerified */ //echo __('Clear Shopping Cart'); ?></span>
        </button>



           -->
        <input type="hidden" value="" id="update_cart_action_container" data-cart-item-update=""/>
<!--        <button type="submit"-->
<!--                name="update_cart_action"-->
<!--                data-cart-item-update=""-->
<!--                value="update_qty"-->
<!--                title="--><?php //echo $block->escapeHtml( __( 'Update Shopping Cart' ) ); ?><!--"-->
<!--                class="action update">-->
<!--            <span>--><?php ///* @escapeNotVerified */
//	            echo __( 'Update Shopping Cart' ); ?><!--</span>-->
<!--        </button>-->
    </div>
</form>
<?php echo $block->getChildHtml( 'checkout.cart.order.actions' ) ?>
<?php echo $block->getChildHtml( 'shopping.cart.table.after' ); ?>

