<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $_shipment = $block->getShipment() ?>
<?php $_order = $block->getOrder() ?>
<?php if ($_shipment && $_order && $_shipment->getAllTracks()): ?>
<br />
<table class="shipment-track" style="width:100%;text-align: left;margin-bottom: 30px;border-spacing: 0;border-collapse: collapse;">
    <thead>
        <tr>
            <th style="padding: 10px 0;font-weight: normal;color: #ab703b;"><?= /* @escapeNotVerified */  __('Shipped By') ?></th>
            <th style="padding: 10px 0;font-weight: normal;color: #ab703b;"><?= /* @escapeNotVerified */  __('Tracking Number') ?></th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($_shipment->getAllTracks() as $_item): ?>
        <tr>
            <td><?= $block->escapeHtml($_item->getTitle()) ?>:</td>
            <td><?= $block->escapeHtml($_item->getNumber()) ?></td>
        </tr>
    <?php endforeach ?>
    </tbody>
</table>
<?php endif; ?>
