<?php
/**
 * Copyright © 2016 Ihor Vansach (ihor@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog post list template
 *
 * @var $block \Magefan\Blog\Block\Post\PostList
 */
?>
<div class="col-md-12">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="innerPage-Title text-center">
                <h4><?php /* @escapeNotVerified */
					echo __( 'Blog' ) ?></h4>
            </div>
        </div>
    </div>
</div>
<div class="clearfix"></div>