<?php
/**
 * Copyright © 2016 Ihor Vansach (ihor@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog post list template
 *
 * @var $block \Magefan\Blog\Block\Post\PostList
 */
?>
<?php
$_postCollection = $block->getPostCollection();

$categoryTitle = "";
if ( method_exists( $block, 'getCategory' ) ) {
	$category      = $block->getCategory();
	$categoryTitle = $category->getTitle();
}

?>
<?php if ( ! $_postCollection->count() ): ?>
    <div class="message info empty">
        <div><?php echo __( 'We can\'t find posts matching the selection.' ) ?></div>
    </div>
<?php else: ?>
    <div class="col-md-12">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <div class="innerPage-Title text-center">
                    <h4><?php /* @escapeNotVerified */
						echo __( 'OUR BLOG' . ( $categoryTitle ? " / " . $categoryTitle : '' ) ) ?></h4>
                    <p><?php /* @escapeNotVerified */
						echo __( 'Follow our latest news and updates.' ) ?></p>
                </div>
            </div>
        </div>
    </div>
    <div class="clearfix"></div>

	<?php echo $block->getAdditionalHtml() ?>

    <div class="post-list-wrapper blog-list">

		<?php $iterator = 1; ?>
        <div class="col3 post-list">
			<?php foreach ( $_postCollection as $_post ): ?>
				<?php echo $block->getPostHtml( $_post ) ?>
			<?php endforeach; ?>
            <li class="hidden">
                <script type="text/javascript">
                    if (window.addthis) {
                        addthis.toolbox('.addthis_toolbox');
                    }
                </script>
            </li>
        </div>
    </div>

	<?php echo $block->getToolbarHtml() ?>

	<?php echo $this->getChildHtml( 'addthisJs' ); ?>
<?php endif; ?>
