<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Category layered navigation
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation
 */
?>

<?php if ($block->canShowBlock()): ?>
    <div class="block filter">
        <div class="block-title filter-title">
            <!-- <strong><?php /* @escapeNotVerified */ // echo __('Shop By') ?></strong> -->
        </div>

        <div class="block-content filter-content">
            <?php echo $block->getChildHtml('state') ?>

            <?php if ($block->getLayer()->getState()->getFilters()): ?>
                <div class="block-actions filter-actions">
                    <a href="<?php /* @escapeNotVerified */ echo $block->getClearUrl() ?>" class="action clear filter-clear"><span><?php /* @escapeNotVerified */ echo __('Clear All') ?></span></a>
                </div>
            <?php endif; ?>
            <?php $wrapOptions = false; ?>
            <?php $i=1; ?>
            <?php $j=1; ?>
            <?php foreach ($block->getFilters() as $filter): ?>
                <?php if (!$wrapOptions): ?>
                    <!-- <strong role="heading" aria-level="2" class="block-subtitle filter-subtitle"><?php /* @escapeNotVerified */ // echo __('Shopping Options') ?></strong> -->
                    <dl class="filter-options" id="narrow-by-list">
                <?php $wrapOptions = true; endif; ?>
                    <?php if ($filter->getItemsCount()): ?>
                        <div class="mw-search-page clearfix">
                            <dt role="heading" aria-level="3" onclick="filterOptions('.filter-options-content-<?php echo $i; ?>')" class="filter-options-title filter-options-title-<?php echo $i; ?>"><?php echo $block->escapeHtml(__($filter->getName())) ?></dt>
                            <dd class="filter-options-content filter-options-content-<?php echo $j; ?>"><?php /* @escapeNotVerified */ echo $block->getChildBlock('renderer')->render($filter); ?></dd>
                        </div>
                        <?php $i++; $j++; ?>
                    <?php endif; ?>
            <?php endforeach; ?>
            <?php if ($wrapOptions): ?>
                </dl>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>

<script type="text/javascript">
var $j = jQuery.noConflict();

function filterOptions(filterOptions){
    $j(filterOptions).toggle(); 
}
    
$j(document).ready(function(){
    $j(".filter-options-content").hide();

    $j("body").click(function(e){


        if( $j(e.target).closest( ".mw-search-page " ).length == 0){
            $j(".filter-options-content").hide();
        }else{
            var $foc = $j(e.target).closest( ".mw-search-page " ).find(".filter-options-content");
            $j(".filter-options-content").not($foc).hide();
        }
        //mw-search-page
    });
});
</script>
<style type="text/css">
    .sidebar.sidebar-additional {
        display: none;
    }
    @media only screen and (max-width: 991px){
        #narrow-by-list .mw-search-page {
            width: 46%;
            float: left;
            margin: 0 2%;
        }
    }
</style>