<?php

/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile
?>
<?php
/**
 * Product list template
 *
 * @var $block \Smartwave\Filterproducts\Block\
 */
?>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
$_portohelper = $this->helper('Smartwave\Porto\Helper\Data');
$review_model = $_portohelper->getModel('\Magento\Review\Model\Review');
$_category_config = $_portohelper->getConfig('porto_settings/category');
$_category_grid_config = $_portohelper->getConfig('porto_settings/category_grid');
$_product_label_config = $this->helper('Smartwave\Porto\Helper\Data')->getConfig('porto_settings/product_label');

$aspect_ratio = $this->getData("aspect_ratio");
if ($aspect_ratio == null) {
    $aspect_ratio = $_category_config['aspect_ratio'];
}
$image_width = $this->getData("image_width");
if (!$image_width) {
    $image_width = ($_category_config['ratio_width']) ? $_category_config['ratio_width'] : 300;
}
$image_height = $this->getData("image_height");
if (!$image_height) {
    $image_height = ($_category_config['ratio_height']) ? $_category_config['ratio_height'] : 300;
}
$move_actions = $this->getData("move_actions");
if ($move_actions == null) {
    $move_actions = $_category_grid_config['move_actions'];
}
$lazy_owl = $this->getData("lazy_owl");
?>
<style>
    #featured_product .filterproducts.products .owl-stage {
        width: 100% !important;
    }
    #featured_product .filterproducts.products .owl-stage .owl-item.active {
        width: 50% !important;
    }
    #featured_product .filterproducts.products .owl-stage .owl-item.active .item.product.product-item {
        width: 48% !important;
        margin: 0 1% !important;
        display: inline-block !important;
    }
</style>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty">
        <div><?php echo __('We can\'t find products matching the selection.') ?></div>
    </div>
<?php else: ?>
    <?php
    $viewMode = 'grid';
    $image = 'category_page_grid';
    $hover_image = 'category_page_grid-hover';
    $showDescription = false;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    ?>
    <div class="products wrapper <?php echo $viewMode; ?> products-<?php echo $viewMode; ?>">
        <?php $iterator = 1; ?>
        <div class="filterproducts products list items product-items">
            <?php $index = 1; ?>
            <?php foreach ($_productCollection as $_product):
                $_product = $objectManager->create('Magento\Catalog\Model\Product')->load($_product->getId());
                ?>
                <?php echo ($iterator++ == 1) ? '<div class="item product col-sm-3 col-md-3">' : '</div><div class="item product col-sm-3 col-md-3">' ?>
                <div class="product-item-info" data-container="product-grid">
                    <?php // Product Image ?>
                    <div class="product photo product-item-photo">
                        <a class="img-hover slide-<?= $_product->getId() ?>" href="<?php echo $_product->getProductUrl() ?>" tabindex="-1"
                           >
                               <?php
                               $product = $objectManager->create('Magento\Catalog\Model\Product')->load($_product->getId());
                               $images = $product->getMediaGalleryImages();
                               $imgcount = count($images);
                               $hoverimgid = 1;
                               $count = 0;
                               foreach ($images as $child) {
                                   $productImage = $_imagehelper->init($product, 'product_page_image_large')
                                           ->setImageFile($child->getFile())->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(TRUE)->resize(200, 200)
                                           ->getUrl();
							   ?>
                                <img class="product-image-photo default_image" style="<?php if ($count != 0) echo "display: none;"; ?>" src="<?php echo $productImage; ?>"/>
                                <?php
                                $count++;
                            }
                            ?>

                        </a>
                        <?php
                        $product_label = "";
                        if ($_product_label_config['sale_label']) {
                            $orgprice = $_product->getPrice();
                            $specialprice = $_product->getSpecialPrice();
                            $specialfromdate = $_product->getSpecialFromDate();
                            $specialtodate = $_product->getSpecialToDate();
                            $today = time();
                            if (!$specialprice)
                                $specialprice = $orgprice;
                            if ($specialprice < $orgprice) {
                                if ((is_null($specialfromdate) && is_null($specialtodate)) || ($today >= strtotime($specialfromdate) && is_null($specialtodate)) || ($today <= strtotime($specialtodate) && is_null($specialfromdate)) || ($today >= strtotime($specialfromdate) && $today <= strtotime($specialtodate))) {
                                    if ($_product_label_config['sale_label_percent']) {
                                        $save_percent = 100 - round(($specialprice / $orgprice) * 100);
                                        $product_label .= '<div class="product-label sale-label">' . '-' . $save_percent . '%' . '</div>';
                                    } else {
                                        $product_label .= '<div class="product-label sale-label">' . $_product_label_config['sale_label_text'] . '</div>';
                                    }
                                }
                            }
                        }
                        if ($_product_label_config['new_label']) {
                            $now = date("Y-m-d");
                            $newsFrom = substr($_product->getData('news_from_date'), 0, 10);
                            $newsTo = substr($_product->getData('news_to_date'), 0, 10);

                            if ($newsTo != '' || $newsFrom != '') {
                                if (($newsTo != '' && $newsFrom != '' && $now >= $newsFrom && $now <= $newsTo) || ($newsTo == '' && $now >= $newsFrom) || ($newsFrom == '' && $now <= $newsTo)) {
                                    $product_label .= '<div class="product-label new-label">' . $_product_label_config['new_label_text'] . '</div>';
                                }
                            }
                        }
                        if ($product_label)
                            echo '<div class="product-labels">' . $product_label . '</div>';
                        ?>
                        <?php if ($_category_config['actions'] && $move_actions): ?>
                            <div class="product-item-inner">
                                <?php
                                $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                                $customerSession = $objectManager->get('Magento\Framework\App\Http\Context');
                                $isLoggedIn = $customerSession->getValue(\Magento\Customer\Model\Context::CONTEXT_AUTH);
                                ?>
                                <?php if ($isLoggedIn) : ?>	
                                    <div class="product actions product-item-actions">
                                        <div class="actions-primary">
                                            <?php if ($_product->isSaleable()): ?>
                                                <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                <form data-role="tocart-form" action="<?php echo $postParams['action']; ?>"
                                                      method="post">
                                                    <input type="hidden" name="product"
                                                           value="<?php echo $postParams['data']['product']; ?>">
                                                    <input type="hidden"
                                                           name="<?php echo Action::PARAM_NAME_URL_ENCODED; ?>"
                                                           value="<?php echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                                           <?php if (isset($_category_config['qty_field']) && $_category_config['qty_field']): ?>
                                                        <div class="qty-box">
                                                            <a href="javascript:void(0)" class="qtyminus"><i
                                                                    class="porto-icon-minus"></i></a>
                                                            <strong>Qty: </strong><input type="text" name="qty" id="qty"
                                                                                         maxlength="12"
                                                                                         value="<?php
                                                                                         /* @escapeNotVerified */
                                                                                         echo $block->getProductDefaultQty() * 1
                                                                                         ?>"
                                                                                         title="<?php
                                                                                         /* @escapeNotVerified */
                                                                                         echo __('Qty')
                                                                                         ?>"
                                                                                         class="input-text qty"
                                                                                         data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"/>
                                                            <a href="javascript:void(0)" class="qtyplus"><i
                                                                    class="porto-icon-plus"></i></a>
                                                        </div>
                                                    <?php endif; ?>
                                                    <?php echo $block->getBlockHtml('formkey') ?>
                                                    <button type="submit"
                                                            title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                            class="action tocart primary">
                                                        <span><?php echo __('Add to Cart') ?></span>
                                                    </button>
                                                </form>
                                            <?php else: ?>
                                                <?php if ($_product->getIsSalable()): ?>
                                                    <div class="stock available"><span><?php echo __('In stock') ?></span>
                                                    </div>
                                                <?php else: ?>
                                                    <div class="stock unavailable">
                                                        <span><?php echo __('Out of stock') ?></span></div>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        </div>
                                        <?php if ($block->getMode() == 'grid'): ?>
                                            <?php if ($_category_config['addtowishlist']): ?>
                                                <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                                    <a href="#"
                                                       class="action towishlist actions-secondary"
                                                       title="<?php echo $block->escapeHtml(__('Add to Favorites')); ?>"
                                                       aria-label="<?php echo $block->escapeHtml(__('Add to Favorites')); ?>"
                                                       data-post='<?php echo $block->getAddToWishlistParams($_product); ?>'
                                                       data-action="add-to-wishlist"
                                                       role="button">
                                                        <span><?php echo __('Add to Wish List') ?></span>
                                                    </a>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                        <?php if ($_category_config['addtocompare']): ?>
                                            <?php
                                            $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
                                            ?>
                                            <a href="#"
                                               class="action tocompare actions-secondary"
                                               title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                               aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                               data-post='<?php echo $compareHelper->getPostDataParams($_product); ?>'
                                               role="button">
                                                <span><?php echo __('Add to Compare') ?></span>
                                            </a>
                                        <?php endif; ?>
                                    </div>
                                <?php endif; ?> 
                            </div>
                        <?php endif; ?>
                    </div>
                    <?php if ($imgcount > 1): ?>
                        <div class="photo-next-pre-container">
                            <span style="float: left;"><a href="javascript:void(0)" class="control_slide" data-id="<?= $_product->getId() ?>" data-btn="prev" ><i class="porto-icon-left-open"></i><?php echo __('PREV') ?></a></span>
                            <span style="float: right"><a href="javascript:void(0)" class="control_slide" data-id="<?= $_product->getId() ?>" data-btn="next"><?php echo __('NEXT') ?><i class="porto-icon-right-open"></i> </a> </span>
                        </div>
                    <?php endif; ?>
                    <div class="product details product-item-details">
                        <?php
                        $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <?php if (!$_category_grid_config['move_title']): ?>
                            <strong class="product name product-item-name">
                                <a class="product-item-link"
                                   href="<?php echo $_product->getProductUrl() ?>">
                                       <?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                </a>
                            </strong>
                        <?php endif; ?>
                        <?php if ($_category_config['rating_star']): ?>
                            <?php
                            $review_model->getEntitySummary($_product);
                            $review_html = $block->getReviewsSummaryHtml($_product, $templateType);
                            ?>
                            <?php if ($review_html): ?>
                                <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
                            <?php else: ?>
                                <div class="product-reviews-summary short">
                                    <div class="rating-summary">
                                        <span class="label"><span>Rating:</span></span>
                                        <div class="rating-result" title="0%">
                                            <span style="width:0"><span>0%</span></span>
                                        </div>
                                    </div>
                                </div>
                            <?php endif; ?>
                        <?php endif; ?>
                        <?php if ($_category_grid_config['move_title']): ?>
                            <div class="product-custom-desc">
                                <strong class="product name product-item-name">
                                    <a class="product-item-link"
                                       href="<?php echo $_product->getProductUrl() ?>">
                                           <?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                    </a>
                                </strong>
                            <?php endif; ?>
                            <?php if ($showDescription): ?>
                                <div class="product description product-item-description">
                                    <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                    <a href="<?php echo $_product->getProductUrl() ?>"
                                       title="<?php echo $_productNameStripped ?>"
                                       class="action more"><?php echo __('Learn More') ?></a>
                                </div>
                            <?php endif; ?>
                            <div class="cat-product-sku"><strong>SKU:</strong> <?php echo $sku = $_product->getSku(); ?>
                            </div>
                            <?php $productupc = $_product->getResource()->getAttribute('upc_code')->getFrontend()->getValue($_product); ?>
                            <?php if (!empty($productupc)): ?>
                                <div class="cate-product-upc"><strong>UPC/EAN: </strong><?php
                                    /* @escapeNotVerified */
                                    echo $productupc;
                                    ?></div>
                            <?php endif; ?>
                            <?php
                            $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                            $customerSession = $objectManager->get('Magento\Framework\App\Http\Context');
                            $isLoggedIn = $customerSession->getValue(\Magento\Customer\Model\Context::CONTEXT_AUTH);
                            ?>

                            <?php if ($isLoggedIn) : ?>

                                <?php if ($_category_config['product_price']): ?>
                                    <?php echo $block->getProductPrice($_product) ?>
                                <?php endif; ?>

                            <?php else: ?>
                                <div class="price-not test"><a href="<?php echo $block->getBaseUrl(); ?>customer/account/login/">Login for Price</a></div>
                            <?php endif; ?>


                        </div>
                        <?php echo $block->getProductDetailsHtml($_product); ?>

                        <?php if ($_category_config['actions'] && !$move_actions): ?>
                            <div class="product-item-inner">
                                <?php
                                $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                                $customerSession = $objectManager->get('Magento\Framework\App\Http\Context');
                                $isLoggedIn = $customerSession->getValue(\Magento\Customer\Model\Context::CONTEXT_AUTH);
                                ?>
                                <?php if ($isLoggedIn) : ?>
                                    <div class="product actions product-item-actions">
                                        <?php if ($block->getMode() == 'grid'): ?>
                                            <?php if ($_category_config['addtowishlist']): ?>
                                                <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                                    <a href="#"
                                                       class="action towishlist actions-secondary <?php if (isset($_category_config['qty_field']) && $_category_config['qty_field']): ?>has-qty<?php endif; ?>"
                                                       title="<?php echo $block->escapeHtml(__('Add to Favorites')); ?>"
                                                       aria-label="<?php echo $block->escapeHtml(__('Add to Favorites')); ?>"
                                                       data-post='<?php echo $block->getAddToWishlistParams($_product); ?>'
                                                       data-action="add-to-wishlist"
                                                       role="button">
                                                        <span><?php echo __('Add to Wish List') ?></span>
                                                    </a>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                        <div class="actions-primary">
                                            <?php if ($_product->isSaleable()): ?>
                                                <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                <form data-role="tocart-form" action="<?php echo $postParams['action']; ?>"
                                                      method="post">
                                                    <input type="hidden" name="product"
                                                           value="<?php echo $postParams['data']['product']; ?>">
                                                    <input type="hidden"
                                                           name="<?php echo Action::PARAM_NAME_URL_ENCODED; ?>"
                                                           value="<?php echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                                           <?php if (isset($_category_config['qty_field']) && $_category_config['qty_field']): ?>
                                                        <div class="qty-box">
                                                            <a href="javascript:void(0)" class="qtyminus"><i
                                                                    class="porto-icon-minus"></i></a>
                                                            <strong>Qty: </strong><input type="text" name="qty" id="qty"
                                                                                         maxlength="12"
                                                                                         value="<?php
                                                                                         /* @escapeNotVerified */
                                                                                         echo $block->getProductDefaultQty() * 1
                                                                                         ?>"
                                                                                         title="<?php
                                                                                         /* @escapeNotVerified */
                                                                                         echo __('Qty')
                                                                                         ?>"
                                                                                         class="input-text qty"
                                                                                         data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"/>
                                                            <a href="javascript:void(0)" class="qtyplus"><i
                                                                    class="porto-icon-plus"></i></a>
                                                        </div>
                                                    <?php endif; ?>
                                                    <?php echo $block->getBlockHtml('formkey') ?>
                                                    <button type="submit"
                                                            title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                            class="action tocart primary">
                                                        <span><?php echo __('Add to Cart') ?></span>
                                                    </button>
                                                </form>
                                            <?php else: ?>
                                                <?php if ($_product->getIsSalable()): ?>
                                                    <div class="stock available"><span><?php echo __('In stock') ?></span>
                                                    </div>
                                                <?php else: ?>
                                                    <div class="stock unavailable">
                                                        <span><?php echo __('Out of stock') ?></span></div>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        </div>
                                        <?php if ($block->getMode() != 'grid'): ?>
                                            <?php if ($_category_config['addtowishlist']): ?>
                                                <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                                    <a href="#"
                                                       class="action towishlist actions-secondary"
                                                       title="<?php echo $block->escapeHtml(__('Add to Favorites')); ?>"
                                                       aria-label="<?php echo $block->escapeHtml(__('Add to Favorites')); ?>"
                                                       data-post='<?php echo $block->getAddToWishlistParams($_product); ?>'
                                                       data-action="add-to-wishlist"
                                                       role="button">
                                                        <span><?php echo __('Add to Wish List') ?></span>
                                                    </a>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                        <?php if ($_category_config['addtocompare']): ?>
                                            <?php
                                            $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
                                            ?>
                                            <a href="#"
                                               class="action tocompare actions-secondary <?php if (isset($_category_config['qty_field']) && $_category_config['qty_field']): ?>has-qty<?php endif; ?>"
                                               title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                               aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                               data-post='<?php echo $compareHelper->getPostDataParams($_product); ?>'
                                               role="button">
                                                <span><?php echo __('Add to Compare') ?></span>
                                            </a>
                                        <?php endif; ?>
                                    </div>
                                <?php endif; ?>
                            </div>
                        <?php endif; ?>
                    </div>
                </div>
                <?php echo ($index == count($_productCollection) + 1) ? '</div>' : '' ?>

                <?php $index++ ?>
            <?php endforeach; ?> <!-- end foreach -->
        </div>
    </div>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
            {
            "[data-role=tocart-form], .form.map.checkout": {
            "catalogAddToCart": {}
            }
            }

        </script>
    <?php endif; ?>
<?php endif; ?>

<style>
    .owl-top-narrow .products.wrapper .product-image-photo.hover-pro-imgs {
        display: none;
    }

</style>
<script type="text/javascript">



    jQuery(function ($) {

        var index = 0;
        jQuery(document).on("click", ".control_slide", function ($) {
            console.log("run");
            var btnType = jQuery(this).data('btn');
            var slideElement = jQuery(this).parent().parent().parent().find(".product > a");
            //console.log(slideElement);

            var allImages = slideElement.find("img");


            if (btnType == "next") {
                index++;
                if (index > (allImages.length - 1)) {
                    index = 0;
                }
            } else if (btnType == 'prev') {
                index--;
                if (index < 0) {
                    index = (allImages.length - 1);
                }

            }

            //console.log(allImages);



            allImages.hide();
            // alert(index);
            jQuery(allImages[index]).show();




        });

    });


</script>
