<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="col-md-12">
                        <div class="row">
                            <div class="col-md-6 col-md-offset-3">
                                <div class="innerPage-Title text-center">
                                    <h4><?php /* @escapeNotVerified */ echo __('CART') ?></h4>
                                </div>
                            </div>
                        </div>
                    </div>