<div id="newsletters_popup_overlay">
	<div id="newsletters_popup">
		<i class="close-btn"></i>
		<div class="newsletter-left">
			<div class="main-image" style="background-image: url(http://wtrlondon.local/tests/newsletter-main.png)"></div>
		</div>
		<div class="newsletter-right">
			<div class="inner">
				<div class="title">Sign up to our weekly newsletter to get</div>
				<div class="subtitle">£10 off your first order</div>
				<div class="cta-image">
					<img src="http://wtrlondon.local/tests/Layer%202.png"/>
				</div>

				<form id="newsletter_form">
					<input type="email" name="newletteremail" placeholder="Enter your email here...">
					<input type="submit" name="submit" value="Submit">
				</form>
			</div>
		</div>
	</div>
</div>