<div class="menu_soort">
	<span><a href="<?php echo  $this->getUrl('') . 'soort-wijn.html';?>">Soort</a></span>
	<div class="menu_soort_submenu">
		<div class="red"><a href="<?php echo  $this->getUrl('') . 'soort-wijn/rode-wijn.html';?>">Rood</a></div>
		<div class="white"><a href="<?php echo  $this->getUrl('') . 'soort-wijn/witte-wijn.html';?>">Wit</a></div>
		<div class="white"><a href="<?php echo  $this->getUrl('') . 'soort-wijn/rose-wijn.html';?>">Rosé</a></div>
		<div class="white"><a href="<?php echo  $this->getUrl('') . 'soort-wijn/mousserende-wijn.html';?>">Mousserend</a></div>
		<div class="white"><a href="<?php echo  $this->getUrl('') . 'soort-wijn/zoet-dessertwijn.html';?>">Zoet / dessertwijn</a></div>
		<div class="white"><a href="<?php echo  $this->getUrl('') . 'soort-wijn/versterkte-wijn.html';?>">Versterkte wijn</a></div>
	</div>
</div>
<div class="menu_land">
	<span><a href="<?php echo  $this->getUrl('') . 'soort-wijn.html';?>">Land</a></span>
	<div class="menu_land_submenu">
		<div class="red"><a href="<?php echo  $this->getUrl('') . 'wijnland/duitsland.html';?>">Duitsland</a></div>
		<div class="white"><a href="<?php echo  $this->getUrl('') . 'wijnland/frankrijk.html';?>">Frankrijk</a></div>
		<div class="white"><a href="<?php echo  $this->getUrl('') . 'wijnland/oostenrijk.html';?>">Oostenrijk</a></div>
		<div class="white"><a href="<?php echo  $this->getUrl('') . 'wijnland/portugal.html';?>">Portugal</a></div>
		<div class="white"><a href="<?php echo  $this->getUrl('') . 'wijnland/spanje.html';?>">Spanje</a></div>
		<div class="white"><a href="<?php echo  $this->getUrl('') . 'wijnland/zwitserland.html';?>">Zwitserland</a></div>
	</div></div>
<div class="menu_druif">
	<span><a href="<?php echo  $this->getUrl('') . 'druif.html';?>">Druif</a></span>
	<div class="menu_druif_submenu">
		<div class="red"><a href="<?php echo  $this->getUrl('') . 'druif.html?druivenras=94';?>">Chardonnay</a></div>
		<div class="red"><a href="<?php echo  $this->getUrl('') . 'druif.html?druivenras=236';?>">Chenin blanc</a></div>
		<div class="red"><a href="<?php echo  $this->getUrl('') . 'druif.html?druivenras=91';?>">Sauvignon blanc</a></div>
		<div class="red"><a href="<?php echo  $this->getUrl('') . 'druif.html?druivenras=82';?>">Veltliner</a></div>
		<div class="red"><a href="<?php echo  $this->getUrl('') . 'druif.html?druivenras=77';?>">Cabernet sauvignon</a></div>
		<div class="red"><a href="<?php echo  $this->getUrl('') . 'druif.html?druivenras=65';?>">Merlot</a></div>
		<div class="red"><a href="<?php echo  $this->getUrl('') . 'druif.html?druivenras=74';?>">Pinot noir</a></div>
		<div class="red"><a href="<?php echo  $this->getUrl('') . 'druif.html?druivenras=66';?>">Syrah</a></div>
		<div class="red"><a href="<?php echo  $this->getUrl('') . 'druif.html?druivenras=79';?>">Zweigelt</a></div>
		<div class="red"><a href="<?php echo  $this->getUrl('') . 'druif.html';?>">Alle druivenrassen</a></div>
	</div></div>
<div class="menu_prijs">
	<span><a href="<?php echo  $this->getUrl('') . 'soort-wijn.html';?>">Prijs</a></span>
	<div class="menu_prijs_submenu">
		<div class="white"><a href="<?php echo  $this->getUrl('') . 'soort-wijn.html?price=-10';?>">0.00 - 9,99</a></div>
		<div class="white"><a href="<?php echo  $this->getUrl('') . 'soort-wijn.html?price=10-20';?>">10,00 - 19,99</a></div>
		<div class="white"><a href="<?php echo  $this->getUrl('') . 'soort-wijn.html?price=20-30';?>">20,00 - 29,99</a></div>
		<div class="white"><a href="<?php echo  $this->getUrl('') . 'soort-wijn.html?price=30-40';?>">30,00 - 39,99</a></div>
		<div class="white"><a href="<?php echo  $this->getUrl('') . 'soort-wijn.html?price=40-50';?>">40,00 - 49,99</a></div>
		<div class="white"><a href="<?php echo  $this->getUrl('') . 'soort-wijn.html?price=70-80';?>">70,00 - 79,99</a></div>
		<div class="white"><a href="<?php echo  $this->getUrl('') . 'soort-wijn.html?price=80-';?>">80,00 en hoger</a></div>

	</div></div>
<div class="menu_horeca">
	<span><a href="<?php echo  $this->getUrl('') . 'horeca.html';?>">Horeca</a></span>
</div>
