<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer */

$_item = $block->getItem();
$product = $_item->getProduct();

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$productInfo = $objectManager->get('\Magento\Catalog\Model\Product')->load($_item->getProductId());

// echo $productInfo->getDescription();exit;

$isVisibleProduct = $product->isVisibleInSiteVisibility();
/** @var \Magento\Msrp\Helper\Data $helper */
$helper = $this->helper('Magento\Msrp\Helper\Data');
$cart_helper = $this->helper('Magento\Checkout\Helper\Cart');
//$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
//$delete_link = $objectManager->create('Magento\Checkout\Block\Cart\Item\Renderer\Actions')->getDeletePostJson($_item);
$delete_link=$cart_helper->getDeletePostJson($_item);

$canApplyMsrp = $helper->isShowBeforeOrderConfirm($product) && $helper->isMinimalPriceLessMsrp($product);
?>

<tbody class="cart item">
    <tr class="item-info">
        <td data-th="<?php echo $block->escapeHtml(__('Item')); ?>" class="col item item-action">
            <?php if ($block->hasProductUrl()):?>
                <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl() ?>"
                   title="<?php echo $block->escapeHtml($block->getProductName()) ?>"
                   tabindex="-1"
                   class="product-item-photo">
            <?php else:?>
                <span class="product-item-photo">
            <?php endif;?>
            
                    
                    
                     <div class="img-container cart-thumbnail-container">
                         <?php echo $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml() ?>
                                        
                                        <a href="#" class="remove-item text-white action action-delete"
   data-post='<?php /* @escapeNotVerified */ echo $delete_link; ?>'>
                                            Remove Item</a>
                                    </div>
            <?php if ($block->hasProductUrl()):?>
                </a>
            <?php else: ?>
                </span>
            <?php endif; ?>
            
        </td>
 <td>
      <?php if ($block->hasProductUrl()):?>
                        <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl() ?>" class="text-primary m-b-20"><?php echo $block->escapeHtml($block->getProductName()) ?></a>
                    <?php else: ?>
                        <?php echo $block->escapeHtml($block->getProductName()) ?>
                    <?php endif; ?>
                                  
                          
                            <?php if ($productInfo->getShortDescription()):?>
                                <?php 
                                echo (strlen($productInfo->getShortDescription()) > 150) ? substr($productInfo->getShortDescription(),0,149).'...' : $productInfo->getShortDescription(); ?>
                            <?php else: ?>
                                <?php 
                                echo (strlen($productInfo->getDescription()) > 150) ? substr($productInfo->getDescription(),0,149).'...' : $productInfo->getDescription();
                                 ?>
                            <?php endif; ?>                           
                          


                                </td>
                                <td>
                                    <div class="color-variation">

                                        <?php if ($_options = $block->getOptionList()):?>
                                          <?php foreach ($_options as $_option) : ?>
                                            <?php if($_option['label']=='COLOR'){
                                              $_formatedOptionValue = $block->getFormatedOptionValue($_option) ;
                                             echo $_formatedOptionValue['value']; 
                                             break;
                                            } 
                                            if(count($_options) < 2){ 
                                              if(!in_array('COLOR', $_option)) {
                                                echo "N/A";
                                              } 
                                            }
                                            ?>
                                          <?php endforeach; ?>
                                          <?php else: ?>
                                            <?php echo "N/A"; ?>
                                        <?php endif; ?>
                                    </div>
                                </td>
                                <td>
                                    <div class="custom-select">
                                      <?php if ($_options = $block->getOptionList()):?>
                                        <?php foreach ($_options as $_option) : ?>
                                        <?php 
                                        if($_option['label']=='SIZE'){
                                          $_formatedOptionValue = $block->getFormatedOptionValue($_option) ;
                                         echo $_formatedOptionValue['value']; 
                                         break;
                                        }
                                        if(count($_options) < 2){ 
                                          if(!in_array('SIZE', $_option)) {
                                            echo "N/A";
                                          }
                                        }
                                       ?>
                                        <?php endforeach; ?>
                                        <?php else: ?>
                                            <?php echo "N/A"; ?>
                                      <?php endif; ?>
                                    </div>
                                </td>
        
       
        <td class="col qty" data-th="<?php echo $block->escapeHtml(__('Qty')); ?>">
            <div class="field qty">
                <div class="control qty">
                    <input id="cart-<?php /* @escapeNotVerified */ echo $_item->getId() ?>-qty"
                           name="cart[<?php /* @escapeNotVerified */ echo $_item->getId() ?>][qty]"
                           data-cart-item-id="<?php /* @escapeNotVerified */ echo $_item->getSku() ?>"
                           value="<?php /* @escapeNotVerified */ echo $block->getQty() ?>"
                           
                           title="<?php echo $block->escapeHtml(__('Qty')); ?>"
                           class="input-text qty product-quantity"
                           
                           data-validate="{required:true,'validate-greater-than-zero':true}"
                           data-role="cart-item-qty"/>
                </div>
            </div>
        </td>
 <?php if ($canApplyMsrp): ?>
            <td class="col msrp" data-th="<?php echo $block->escapeHtml(__('Price')); ?>">
                <span class="pricing msrp">
                    <span class="msrp notice"><?php /* @escapeNotVerified */ echo __('See price before order confirmation.'); ?></span>
                    <?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
                    <a href="#" class="action help map" id="<?php /* @escapeNotVerified */ echo($helpLinkId); ?>" data-mage-init='{"addToCart":{"helpLinkId": "#<?php /* @escapeNotVerified */ echo $helpLinkId;?>","productName": "<?php /* @escapeNotVerified */ echo $product->getName(); ?>","showAddToCart": false}}'>
                        <span><?php /* @escapeNotVerified */ echo __("What's this?"); ?></span>
                    </a>
                </span>
            </td>
        <?php else: ?>
            <td class="col price" data-th="<?php echo $block->escapeHtml(__('Price')); ?>">
                <?php echo $block->getUnitPriceHtml($_item); ?>
            </td>
        <?php endif; ?>
        <td class="col subtotal" data-th="<?php echo $block->escapeHtml(__('Subtotal'));?>">
            <?php if ($canApplyMsrp): ?>
                <span class="cart msrp subtotal">--</span>
            <?php else: ?>
                <?php echo $block->getRowTotalHtml($_item); ?>
            <?php endif; ?>
        </td>
    </tr>
<!--    <tr class="item-actions">
        <td colspan="100">
            <div class="actions-toolbar">
                <?php /* @escapeNotVerified */ //echo $block->getActions($_item) ?>
            </div>
        </td>
    </tr>-->
</tbody>
