<div class="social_free">
	<p class="title">Lekker social</p>
	<p class="detail">U vindt ons regelmatig op de sociale media. Check it out!</p>
	<div class="icons">
		<a href="https://www.facebook.com/www.lekkersapje.nl/"><i class="fa fa-facebook" aria-hidden="true"></i></a>
		<a href="https://twitter.com/lekkersapje"><i class="fa fa-twitter" aria-hidden="true"></i></a>
		<a href="https://www.instagram.com/lekkersapje/"><i class="fa fa-instagram" aria-hidden="true"></i></a>
	</div>
</div>