<div class="blog">
	<div class="title"><span>Blog</span></div>
	<div class="content">
		<div class="image">
			<img src="<?php echo $this->getSkinUrl('images/homepage/blog/main.jpg', array('_secure'=>true));?>"/>
			<div class="main_content">
				<div class="main_title">
					<span>Lorem ipsum dolor sit amet, consectetur </span>
				</div>
				<div class="main_detail">
					<span>adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit </span>
				</div>
			</div>
		</div>
		<div class="description">
			<div class="first">
				<div class="blog_detail">
					<div class="sub_title"><span>Lorem ipsum dolor sit amet,</span></div>
					<div class="sub_content"><span>Dipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit,</span></div>
				</div>
				<div class="blog_image">
					<img src="<?php echo $this->getSkinUrl('images/homepage/blog/first.jpg', array('_secure'=>true));?>"/>
				</div>
			</div>
			<div class="second">
				<div class="blog_detail">
					<div class="sub_title"><span>Lorem ipsum dolor sit amet</span></div>
					<div class="sub_content"><span>adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit,</span></div>
				</div>
				<div class="blog_image">
					<img src="<?php echo $this->getSkinUrl('images/homepage/blog/second.jpg', array('_secure'=>true));?>"/>
				</div>
			</div>
			<div class="third">
				<div class="blog_detail">
					<div class="sub_title"><span>Lorem ipsum dolor sit amet</span></div>
					<div class="sub_content"><span>adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit,</span></div>
				</div>
				<div class="blog_image">
					<img src="<?php echo $this->getSkinUrl('images/homepage/blog/third.jpg', array('_secure'=>true));?>"/>
				</div>
			</div>
		</div>
	</div>
</div>