<div class="workshops">
	<div class="title"><span>Workshops</span></div>
	<div class="first col-lg-4 col-md-4 col-sm-12 col-xs-12">
		<img src="<?php echo $this->getSkinUrl('images/homepage/workshops/first.jpg', array('_secure'=>true));?>"/>
		<div class="description">
			<div class="title"><span>Workshop</span></div>
			<div class="detail"><span>What's for dinner?</span></div>
			<div class="date"><span>Tuesday 17 juli</span></div>
		</div>
	</div>
	<div class="second col-lg-4 col-md-4 col-sm-12 col-xs-12">
		<img src="<?php echo $this->getSkinUrl('images/homepage/workshops/second.jpg', array('_secure'=>true));?>"/>
		<div class="description">
			<div class="title"><span>Workshop</span></div>
			<div class="detail"><span>Food for thought</span></div>
			<div class="date"><span>Tuesday 17 juli</span></div>
		</div>
	</div>
	<div class="third col-lg-4 col-md-4 col-sm-12 col-xs-12">
		<img src="<?php echo $this->getSkinUrl('images/homepage/workshops/third.jpg', array('_secure'=>true));?>"/>
		<div class="description">
			<div class="title"><span>Workshop</span></div>
			<div class="detail"><span>Summer food</span></div>
			<div class="date"><span>Tuesday 17 juli</span></div>
		</div>
	</div>
	<div class="more-workshops"><a href="<?php echo Mage::getBaseUrl() . "workshops.html";?>"><span>View Workshops »</span></a></div>
	<div class="separate">
		<img src="<?php echo $this->getSkinUrl('images/homepage/workshops/separate.jpg', array('_secure'=>true));?>"/>
	</div>
</div>
