<?php

$devices = $block->getDevices();

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();

$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');

$productCollectionFactory = $objectManager->get('Magento\Catalog\Model\ResourceModel\Product\CollectionFactory');
?>

<?php if ($devices) {

    ?>





        <div class="row">

            <ul class="subchildmenu">

                <?php

                foreach ($devices as $key => $device) {
					

                    $collection = $productCollectionFactory->create();

                    $collection->addAttributeToSelect('*');
					
					$collection->addAttributeToFilter('devices_magento', array('like' => "%" . $device['value'] . "%"));
					
					$collection->addAttributeToFilter('status',Magento\Catalog\Model\Product\Attribute\Source\Status::STATUS_ENABLED);
					
					$collection->load();
					
                    $counts = count($collection);

                    if($counts==0) continue;

                    if ($key != 0) {

                        ?>



                        <li class="ui-menu-item level1 <?php echo $counts; ?>">
						
						<?php 
						$temp_str = str_replace(array(" ", '.', '/', "  "),"-",$device['label']);
						$temp_str = str_replace(array('(', ')'),"",$temp_str);
						$temp_str = str_replace('--',"-",$temp_str);
						?>

									<a href="<?= $storeManager->getStore()->getBaseUrl() . "all-products?devices_magento=" . $device['value']; ?>"

                                    style="font-weight: 600;color: #696969;margin-top: 0"><?= $device['label'] ?></a>

                        </li>



                        <?php

                    }

                    ?>



                    <?php

                }

                ?>





            </ul>

        </div>




    <?php

} else {

    ?>

    <div class="container" style="padding-top:20px">

        <p><b>No Manufacture found.</b></p>

    </div>



    <?php

}

