<?php
$brands = $block->getBrands();
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$productCollectionFactory = $objectManager->get('Magento\Catalog\Model\ResourceModel\Product\CollectionFactory');
?>
<?php if ($brands) {
    ?>

    <div class="container">
        <div class="row">
            <ul class="subchildmenu col-sm-12 mega-columns columns6">
                <?php
                foreach ($brands as $key => $brand) {
                    $collection = $productCollectionFactory->create();
                    $collection->addAttributeToSelect('*');
                    $collection->addAttributeToFilter('manufacturer', $brand['value']);
					$collection->addAttributeToFilter('status',Magento\Catalog\Model\Product\Attribute\Source\Status::STATUS_ENABLED);
                    $counts = count($collection);
                    if($counts==0) continue;
                    if ($key != 0) {
                        ?>

                        <li class="ui-menu-item level1 <?php echo $counts;?>">
						
						<?php 
						$temp_str = str_replace(array(" ", '.', '/', "  "),"-",$brand['label']);
						$temp_str = str_replace(array('(', ')'),"",$temp_str);
						$temp_str = str_replace('--',"-",$temp_str);
						?>
						
						<a href="<?= $storeManager->getStore()->getBaseUrl() . "all-products?manufacturer=" . $brand['value']; ?>"
                                    style="font-weight: 600;color: #696969;margin-top: 0"><?= $brand['label'] ?></a>
                        </li>

                        <?php
                    }
                    ?>

                    <?php
                }
                ?>
				<?php 
				/*foreach ($brands as $brand) {
					foreach ($brand as $sub_brand) {
						foreach ($sub_brand as $main_brand) {
							?>
							<!--<li class="ui-menu-item level1"><a
                                    href="<?= $main_brand['url']?>"
								style="font-weight: 600;color: #696969;margin-top: 0"><?= $main_brand['label'] ?></a>
							</li>-->
							<?php
						}
					}
                }*/
				?>

            </ul>
        </div>
    </div>

    <?php
} else {
    ?>
    <div class="container" style="padding-top:20px">
        <p><b>No Manufacture found.</b></p>
    </div>

    <?php
}
