<?php
$models = $block->getModels();
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$productCollectionFactory = $objectManager->get('Magento\Catalog\Model\ResourceModel\Product\CollectionFactory');
?>
<?php if ($models) {
    ?>

        <div class="row">
            <ul class="subchildmenu">
                <?php
                foreach ($models as $key => $model) {
                    $collection = $productCollectionFactory->create();
                    $collection->addAttributeToSelect('*');
                    $collection->addAttributeToFilter('model', $model['value']);
					$collection->addAttributeToFilter('status',Magento\Catalog\Model\Product\Attribute\Source\Status::STATUS_ENABLED);
                    $counts = count($collection);
                    if($counts==0) continue;
                    if ($key != 0) {
                        ?>

                        <li class="ui-menu-item level1">
						
						<?php 
						$temp_str = str_replace(array(" ", '.', '/', "  "),"-",$model['label']);
						$temp_str = str_replace(array('(', ')'),"",$temp_str);
						$temp_str = str_replace('--',"-",$temp_str);
						?>
						
						<a href="<?= $storeManager->getStore()->getBaseUrl() . strtolower($temp_str) . "?model=" . $model['value'] . "&model_name=" . $model['label']; ?>"
                                    style="font-weight: 600;color: #696969;margin-top: 0"><?= $model['label'] ?></a>
                        </li>

                        <?php
                    }
                    ?>

                    <?php
                }
                ?>


            </ul>
        </div>

    <?php
} else {
    ?>
    <div class="container" style="padding-top:20px">
        <p><b>No Model found.</b></p>
    </div>

    <?php
}
