<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var $block \Magento\Review\Block\Form
 */
?>
<!--<div class="block review-add write-a-review-container">-->


<div class="write-a-review-container" >
                            <h5 class="text-primary m-b-20"><?php /* @escapeNotVerified */ echo __('WRITE A REVIEW') ?></h5>
                            
                            <?php if ($block->getAllowWriteReviewFlag()): ?>
                            <form action="<?php /* @escapeNotVerified */ echo $block->getAction() ?>" class="review-form" method="post" id="review-form" data-role="product-review-form" data-bind="scope: 'review-form'">
    <?php echo $block->getBlockHtml('formkey'); ?>
    <?php echo $block->getChildHtml('form_fields_before')?>
    <div class="col-md-12">
<div class="row">
                             <div class="col-md-6 col-sm-6">
                                    <div class="form-group">
                                        <label for="name"><?php /* @escapeNotVerified */ echo __('Name') ?></label>
                                        <input type="text" name="nickname" placeholder="Enter Your Name" id="nickname_field" class="input-text" data-validate="{required:true}" data-bind="value: nickname()" />
                                    </div>
                                </div>
                                <!-- <div class="col-md-6 col-sm-6">
                                    <div class="form-group">
                                        <label for="name">Email</label>
                                        <input type="email" id="email" placeholder="Enter Your Email">
                                    </div>
                                </div> -->
                               
                                <div class="col-md-6 col-sm-6">
                                    <div class="form-group">
                                        <label for="name"><?php /* @escapeNotVerified */ echo __('Review Title') ?></label>
                                        <input type="text" name="title" id="summary_field" class="input-text" placeholder="Give Your Review a Title" data-validate="{required:true}" data-bind="value: review().title" />
                                    </div>
                                </div>
                                <?php if ($block->getRatings() && $block->getRatings()->getSize()): ?>
                                <div class="col-md-6 col-sm-6">
                                    <div class="rate-product-stars form-group">
                                        <label for="rate-product"><?php /* @escapeNotVerified */ echo __('Rating') ?></label>
                                        <?php foreach ($block->getRatings() as $_rating): ?>
                        <div class="field choice review-field-rating rate-product">                            
                            <div class="control review-control-vote">
                            <?php $options = $_rating->getOptions();?>
                            <?php $iterator = 1; foreach ($options as $_option): ?>
                                <input
                                    type="radio"
                                    name="ratings[<?php /* @escapeNotVerified */ echo $_rating->getId() ?>]"
                                    id="<?php echo $block->escapeHtml($_rating->getRatingCode()) ?>_<?php /* @escapeNotVerified */ echo $_option->getValue() ?>"
                                    value="<?php /* @escapeNotVerified */ echo $_option->getId() ?>"
                                    class="radio"
                                    data-validate="{required:true, messages:{required:'Please select one of each of the ratings above.'}}"
                                    aria-labelledby="<?php echo $block->escapeHtml($_rating->getRatingCode()) ?>_rating_label <?php echo $block->escapeHtml($_rating->getRatingCode()) ?>_<?php /* @escapeNotVerified */ echo $_option->getValue() ?>_label" />
                                <label
                                    class="rating-<?php /* @escapeNotVerified */ echo $iterator; ?>"
                                    for="<?php echo $block->escapeHtml($_rating->getRatingCode()) ?>_<?php /* @escapeNotVerified */ echo $_option->getValue() ?>"
                                    title="<?php /* @escapeNotVerified */ echo __('%1 %2', $iterator, $iterator > 1 ? 'stars' : 'star') ?>"
                                    id="<?php echo $block->escapeHtml($_rating->getRatingCode()) ?>_<?php /* @escapeNotVerified */ echo $_option->getValue() ?>_label">
                                    <span><?php /* @escapeNotVerified */ echo __('%1 %2', $iterator, $iterator > 1 ? 'stars' : 'star') ?></span>
                                </label>
                            <?php $iterator++; ?>
                            <?php endforeach; ?>
                            </div>
                        </div>
                    <?php endforeach; ?>
                                        
                                    </div>
                                    <div class="clearfix"></div>
                                </div>
                                <?php endif ?>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="name"><?php /* @escapeNotVerified */ echo __('Review') ?></label>
                                        <textarea name="detail" id="review_field" cols="5" rows="3" placeholder="Write Your Comments Here" data-validate="{required:true}" data-bind="value: review().detail"></textarea>
                                    </div>
                                </div>
                                <div class="col-md-12 text-center">
                                    <button type="submit" class="action submit btn btn-primary"><span><?php /* @escapeNotVerified */ echo __('SUBMIT REVIEW') ?></span></button>
                                </div>
                                </div>
                                </div>
                            </form>
<script type="text/x-magento-init">
{
    "[data-role=product-review-form]": {
        "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>
    },
    "#review-form": {
        "Magento_Review/js/error-placement": {}
    }
}
</script>
<?php else: ?>
    <div class="message info notlogged" id="review-form">
        <div>
            <?php /* @escapeNotVerified */ echo __('Only registered users can write reviews. Please <a href="%1">Sign in</a> or <a href="%2">create an account</a>', $block->getLoginLink(), $block->getRegisterUrl()) ?>
        </div>
    </div>
<?php endif ?>
</div>    