<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>

<?php /** @var $_order \Magento\Sales\Model\Order */ 
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$formatedAddress = $objectManager->create('\Magento\Sales\Model\Order\Email\Sender\OrderSender');
?>
<?php $_order = $block->getOrder();  ?>

<?php if ($_order): ?>
    <?php $_items = $_order->getAllItems(); ?>
    <table class="email-items" style="width:100%;text-align: left;margin-bottom: 30px;border-spacing: 0;border-collapse: collapse;">
        <thead>
            <tr>
                <th class="item-info" style="padding: 10px 0;border-bottom: 1px solid #ddd;font-weight: normal;color: #ab703b;">
                    <?= /* @escapeNotVerified */  __('ITEMS'); ?>
                </th>
                <th class="item-price" style="padding: 10px 0;border-bottom: 1px solid #ddd;font-weight: normal;color: #ab703b;">
                    <?= /* @escapeNotVerified */  __('PRICE'); ?>
                </th>
                <th class="item-qty" style="padding: 10px 0;border-bottom: 1px solid #ddd;font-weight: normal;color: #ab703b;">
                    <?= /* @escapeNotVerified */  __('QUANTITY'); ?>
                </th>
                <th class="item-price" style="padding: 10px 0;border-bottom: 1px solid #ddd;font-weight: normal;color: #ab703b;">
                    <?= /* @escapeNotVerified */  __('TOTAL'); ?>
                </th>
            </tr>
        </thead>
        <?php foreach ($_items as $_item): ?>
            <?php
                if ($_item->getParentItem()) {
                    continue;
                }
            ?>
            <tbody>
                <?= $block->getItemHtml($_item) ?>
            </tbody>
        <?php endforeach; ?>
    </table>
    <table style="width: 100%">
        <tbody style="width: 50%;float: left;">
            <tr style="width: 100%;float: left;">
                <td style="width: 90%;float: left;">
                    <div class="invoice">
						
                        <div style="display: table;content: '';clear: both;"></div>
                    </div>
                </td>
            </tr>
        </tbody>
        <tfoot class="order-totals total" style="width: 50%;float: right;">
            <?= $block->getChildHtml('order_totals') ?>
        </tfoot>
    </table>
    <?php if ($this->helper('Magento\GiftMessage\Helper\Message')->isMessagesAllowed('order', $_order, $_order->getStore()) && $_order->getGiftMessageId()): ?>
        <?php $_giftMessage = $this->helper('Magento\GiftMessage\Helper\Message')->getGiftMessage($_order->getGiftMessageId()); ?>
        <?php if ($_giftMessage): ?>
            <br />
            <table class="message-gift">
                <tr>
                    <td>
                        <h3><?= /* @escapeNotVerified */  __('Gift Message for this Order') ?></h3>
                        <strong><?= /* @escapeNotVerified */  __('From:'); ?></strong> <?= $block->escapeHtml($_giftMessage->getSender()) ?>
                        <br /><strong><?= /* @escapeNotVerified */  __('To:'); ?></strong> <?= $block->escapeHtml($_giftMessage->getRecipient()) ?>
                        <br /><strong><?= /* @escapeNotVerified */  __('Message:'); ?></strong>
                        <br /><?= $block->escapeHtml($_giftMessage->getMessage()) ?>
                    </td>
                </tr>
            </table>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>
