<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\Catalog\Block\Product\AbstractProduct */
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
?>

<?php
switch ($type = $block->getType()) {

    case 'related-rule':
        if ($exist = $block->hasItems()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = true;
            $showCart = false;
            $templateType = null;
            $description = false;
        }
    break;

    case 'related':
        /** @var \Magento\Catalog\Block\Product\ProductList\Related $block */
        if ($exist = $block->getItems()->getSize()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getItems();
            $limit = 0;
            $shuffle = 0;
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = true;
            $showCart = false;
            $templateType = null;
            $description = false;
        }
    break;

    case 'upsell-rule':
        if ($exist = $block->hasItems()) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();

            $showAddTo = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'upsell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Upsell $block */
        if ($exist = count($block->getItemCollection()->getItems())) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getItemCollection()->getItems();
            $limit = $block->getItemLimit('upsell');
            $shuffle = 0;

            $showAddTo = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'crosssell-rule':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->hasItems()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItemCollection();

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'crosssell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->getItemCount()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItems();

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'new':
        if ($exist = $block->getProductCollection()) {
            $type = 'new';
            $mode = 'grid';
            $type = $type . ' ' . $mode;

            $class = 'widget' . ' ' . $type;

            $image = 'new_products_content_widget_grid';
            $title = __('New Products');
            $items = $exist;

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = ($mode == 'list') ? true : false;
            $canItemsAddToCart = false;
        }
    break;

    case 'other':
    break;
}
?>






<?php if ($exist):?>



    <?php if ($type == 'related' || $type == 'upsell'): ?>
        <?php if ($type == 'related'): ?>
            <div class="block <?php /* @escapeNotVerified */ echo $class; ?>" data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}' data-limit="<?php /* @escapeNotVerified */ echo $limit; ?>" data-shuffle="<?php /* @escapeNotVerified */ echo $shuffle; ?>">
        <?php else: ?>
            <div class="block <?php /* @escapeNotVerified */ echo $class; ?>" data-mage-init='{"upsellProducts":{}}' data-limit="<?php /* @escapeNotVerified */ echo $limit; ?>" data-shuffle="<?php /* @escapeNotVerified */ echo $shuffle; ?>">
        <?php endif; ?>
    <?php else: ?>
        <div class="block <?php /* @escapeNotVerified */ echo $class; ?>">
    <?php endif; ?>
  <h4 class="text-center"><?php /* @escapeNotVerified */ echo __('MATCH IT WITH') ?></h4>            
                    <div class="col3 m-t-30">
                        <?php $iterator = 1; ?>
                <?php foreach ($items as $_item): ?>
                         <?php
                            
        $product = $objectManager->create('Magento\Catalog\Model\Product')->load($_item->getId());        
   $images = $product->getMediaGalleryImages(); 
   $i=1;
   if(!empty($images)){
       ?>
                        
       <?php 
      foreach($images as $child):
          if($i>2){
              break;
          }
          $image_list[]=$child->getUrl();
          
     $i++; endforeach;?>
   <?php } ?> 
                         <div class="col-md-3 col-sm-4">
                            <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" class="col-3-content">
                                
                                <p class="img-holder background-image flip-front">
         <img src="<?php echo $image_list[0]; ?>" alt='<?php echo $block->escapeHtml($_item->getName()) ?>' >
         <span class="img-holder background-image flip-back">
        <img src="<?php echo isset($image_list[1])?$image_list[1]:$image_list[0]; ?>" alt='<?php echo $block->escapeHtml($_item->getName()) ?>' >
        </span>
 <?php unset($image_list); ?>
    
                    </p>
                    </a>
                    <span class="col-4-details shop-product-detail">
                        <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>"><h6><?php echo $block->escapeHtml($_item->getName()) ?></h6></a>
                        <?php  $priceHelper = $objectManager->create('Magento\Framework\Pricing\Helper\Data');
                         $price = $_item->getPriceInfo()->getPrice('final_price','')->getValue();
                         $formattedPrice = $priceHelper->currency($price, true, false);?>
                        <?php /* <p><?php echo $formattedPrice?></p> */ ?>
                    <?php $id = $_item->getId();
                          $regular_price  = $_item->getPriceInfo()->getPrice('regular_price')->getValue();
                          $final_price = $_item->getPriceInfo()->getPrice('final_price')->getValue();                           
                    ?>                   
                    <div class="price-box price-final_price" data-role="priceBox" data-product-id="<?php echo $id;?>">
                        <?php if($final_price < $regular_price) {?>
                        <span class="special-price">
                            <span class="price-container price-final_price tax weee">
                            <h6 class="product-price m-t-30" id="final-price-<?php echo $id;?>" data-price-amount="<?php echo $final_price;?>" data-price-type="finalPrice"> <?php echo $priceHelper->currency($final_price, true, false);?></h6>
                            </span>
                        </span>
                        <?php } else{ ?>                        
                            <span class="price-container price-final_price tax weee">
                            <h6 class="product-price m-t-30" id="old-price-<?php echo $id;?>" data-price-amount="<?php echo $regular_price;?>" data-price-type="oldPrice"><?php echo $priceHelper->currency($final_price, true, false);?></h6>    
                            </span>
                        <?php } ?>                        
                    <span class="old-price sly-old-price no-display">
                        <span class="price-container price-final_price tax weee">
                        <h6 class="product-price m-t-30" id="old-price-<?php echo $id;?>" data-price-amount="<?php echo $regular_price;?>" data-price-type="oldPrice"><?php echo $priceHelper->currency($regular_price, true, false);?></h6>    
                        </span>
                    <?php if($final_price < $regular_price) {?>
                    <script type="text/javascript">
                        var prod_id = '<?php echo $_item->getId(); ?>';                                    
                        jQuery("#old-price-"+prod_id).parent().parent().css('display','block');
                    </script>
                    <?php } ?>
                    </span>
                    </div> 

                            </span><div class="clearfix"></div>
                        </div>
                        <?php  endforeach; ?>
                       

                        <div class="clearfix"></div>
                    </div>
                
    <?php endif; ?>               

