<?php
/**
 * Copyright © 2015 Ihor Vansach (ihor@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog post list item template
 *
 * @var $block \Magefan\Blog\Block\Post\AbstractPost
 */
?>
<?php
    $_post = $this->getPost();
    $_postUrl = $_post->getPostUrl();
    $_postName = $block->escapeHtml($_post->getTitle(), null, true);
?>

<div class="col-md-4 col-sm-6 post-list-item  post-holder-<?php echo $_post->getId() ?>">
                            <a href="<?php echo $_postUrl ?>" class="col-3-content">
                                 <?php if ($featuredImage = $_post->getFeaturedImage()) { ?>
                                <p class="img-holder background-image" >
                                   
           
                                 <img src="<?php echo str_replace("\\", "/", $featuredImage); ?>" alt="<?php echo $_postName ?>" class="" >
            
                                 <span class="hover-overlay"></span>
                                </p>
                                <?php } ?>
                            </a>
                            <div class="col-3-details blog-details" style="height: 178px;">
                                <h5><a  class="post-item-link" href="<?php echo $_postUrl ?>"><?php echo $_postName; ?></a></h5>
                               <?php echo $block->getShorContent() ?>
                                <span class="blog-meta blog-author"> <?php if ($_author = $_post->getAuthor()) { ?>  <?php echo $block->escapeHtml($_author->getTitle()) ?>  <?php } ?></span> <span class="blog-meta blog-date"><?php echo $_post->getPublishDate('F d, Y') ?></span>
                                
                            </div>
                        </div>
