<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Checkout\Block\Onepage\Success */ ?>
<div class="checkout-success">
	<?php if ( $block->getOrderId() ): ?>
    <div class="col-md-12">
        <ul class="opc-progress-bar new">
            <li class="opc-progress-bar-item _active">
                <span>Shopping Bag</span>
            </li>
            <li class="opc-progress-bar-item _active">
                <span>Shipping Detail</span>
            </li>
            <li class="opc-progress-bar-item _active">
                <span>Billing & Payment Details</span>
            </li>
            <li class="opc-progress-bar-item _active">
                <span>Order Confirmation</span>
            </li>
        </ul>
    </div>

    <div class="col-md-12 mw-order-message text-center">
        <h2><?php echo __( 'THANK YOU FOR YOUR PURCHASE' ) ?></h2>
        <p><?php echo __( 'Please contact our Flagship Store for our after care service, we look forward to hearing from you.' ); ?></p>
    </div>

    <div class="col-md-10 col-md-push-1 mw-order-message-box">
        <div class="row">
            <div class="col-md-6 mw-order-message-box-set-1">
				<?php if ( $block->getCanViewOrder() ) : ?>
                    <p><?php echo __( 'Your order number is: %1.', sprintf( '<a href="%s" class="order-number"><strong>%s</strong></a>', $block->escapeHtml( $block->getViewOrderUrl() ), $block->escapeHtml( $block->getOrderId() ) ) ) ?></p>
				<?php else : ?>
                    <p><?php echo __( 'Your order # is: <span>%1</span>.', $block->escapeHtml( $block->getOrderId() ) ) ?></p>
				<?php endif; ?>
                <p><?php /* @escapeNotVerified */
					echo __( 'We\'ll email you an order confirmation with details and tracking info.' ) ?></p>
                <div class="actions-toolbar mw">
                    <div class="primary">
                        <a class="action primary continue" href="<?php /* @escapeNotVerified */
						echo $block->getUrl() ?>"><span><?php /* @escapeNotVerified */
								echo __( 'Continue Shopping' ) ?></span></a>
                    </div>
                </div>
            </div>
			<?php endif; ?>
            <div class="col-md-6 mw-order-message-box-set-2">
				<?php echo $block->getAdditionalInfoHtml() ?>
                <div id="create-registration" class="hide create-registration"></div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    var $j = jQuery.noConflict();
    $j(document).ready(function () {

        if ($j("#create-registration").hasClass("create-registration")) {
            $j("#registration").insertAfter($j(".create-registration"));
            /*sucess page fix*/
        }

    });
</script>

<script type="text/javascript">
    dataLayer.push({
        'event': 'gtm.orderComplete',
        'eventValue': "<?php echo $block->escapeHtml( $block->getOrderId() ); ?>"
    });
</script>


