<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
use Magento\Catalog\Model\Product\ProductList\Toolbar;
?>
<div class="sortBy">
    <div class="custom-select">
        <span>Sort By: </span>
        <select class="sortBy-select" name="sortBy">            
            <?php foreach ($block->getAvailableOrders() as $_key => $_order): ?>
                <option value="<?php /* @escapeNotVerified */ echo $_key; ?>"
                    <?php if ($block->isOrderCurrent($_key)): ?>
                        selected="selected"
                    <?php endif; ?>
                    >
                    <?php echo $block->escapeHtml(__($_order)) ?>
                </option>
            <?php endforeach; ?>
        </select>
    </div>
</div>
