<div class="consult_page">
	<div class="main_slider owl-carousel">
		<div class="item">
		<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('consult-slide-1')->toHtml() ?>
		</div>
	</div>
	<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('consult-content')->toHtml() ?>
</div>
<script>
	jQuery(document).ready(function($) {
		var owl = $('.consult_page .main_slider');
		owl.owlCarousel({
			items:1,
			loop:false,
			dots: 0,
			stagePadding:0,
			margin:10,
			autoplay:false,
			autoplayTimeout:5000,
			autoplayHoverPause:false
		});
	});
</script>



