<div class="contact_page">
	<div class="content">
		<div class="sub_content">
		<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('contact-intro')->toHtml() ?>
		</div>
		<div class="image">
			<img src="<?php echo $this->getSkinUrl('images/contactpage/main.jpg');?>"/>
		</div>
	</div>
		<a name="faq"></a>
	<div class="faq_block">
		<div class="title">
			<span>Frequently Asked Questions</span><br>
			<span>About You</span>
		</div>
		<div class="question_block">
		<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('contact-faq1')->toHtml() ?>
		</div>
	</div>
	<div class="faq_block">
		<div class="title">
			<span>About the Workshop</span>
		</div>
		<div class="question_block">
		<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('contact-faq2')->toHtml() ?>
		</div>
	</div>
		<div class="faq_block">
		<div class="title">
			<span>After the Workshop</span>
		</div>
		<div class="question_block">
		<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('contact-faq3')->toHtml() ?>
		</div>
	</div>
	
	<!--	<div class="terms_block">
		<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('contact-terms')->toHtml() ?>
	</div>-->

</div>
<script>
	jQuery(document).ready(function($) {
		$(".contact_page .question_title").click(function(){
			$(this).parent().find(".question_content").slideToggle("slow");
			if ($(this).parent().hasClass("active")) {
				$(this).parent().removeClass("active");
			} else {
				$(this).parent().addClass("active");
			}
		});
	});
</script>