<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /* @escapeNotVerified */ echo $block->getMiscellaneousHtml(); ?>

<?php $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$baseUrl = $storeManager->getStore()->getBaseUrl();

?>

<!-- Modal -->
<div class="modal" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-body">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>

        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('modal_welcome_text_contnet')->toHtml();?>
		<div class="text-center subscribe-bottom">
	        <input id="newsletter_popup_dont_show_again" type="checkbox">
	        <label for="newsletter_popup_dont_show_again">Don't show this popup again</label>
	        <p><?php //echo "val-".$cookievalue;?>	</p>        
	    </div>
        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('modal_link_contnet')->toHtml();?>

      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
	var f = jQuery.noConflict();

	f(window).load(function () {
    
var cookieval = '';
jQuery.ajax({
    url : '<?php echo $baseUrl; ?>/customcheckout/cookie/readcookie',
    async: false,
    type: 'post',
    //data : {duration:duration},
    dataType: 'text',
      success: function(result){
          cookieval = result;                                        
      }
  });
  //console.log("after ajax cookieee-"+cookieval);           

		"use strict";
    //  if(cookieval != 'isshown'){      
		  //   f('#myModal').modal('show');
    // }
	});


 jQuery("#myModal").on("hidden.bs.modal", function () {  
   var duration = 6400;
   jQuery.ajax({
    url : '<?php echo $baseUrl; ?>/customcheckout/cookie/addcookie',
    type: 'post',
    data : {duration:duration},
    dataType: 'text',
      success: function(result){
               //console.log(result);                                
      }
  });
 });
 jQuery("#newsletter_popup_dont_show_again").click(function(){
  //set cookie value
  var duration = 172800;
  jQuery.ajax({
  	url : '<?php echo $baseUrl; ?>/customcheckout/cookie/addcookie',
  	type: 'post',
    data : {duration:duration},
    dataType: 'text',
      success: function(result){
               //console.log(result);                                
      }
  });

});
</script>

<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('newsletter-pop')->toHtml();?>
<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('cookie_bottom_bar')->toHtml();?>
