<div class="container">
	<div class="title"><h1>Leading Magento Development Company In Europe</h1></div>
	<div class="content">
		<p>As a prestigious Magento development company with over 5-year-experience of e-commerce design, building, maintenance and business know-how, we have strong expertise to build professional and user-friendly online stores that guarantee your sales! We offer a wide range of exceptional Magento development services from Magento website design and development, Magento optimization, Magento migration, Magento support to Magento mobile app development. Besides, we focus on developing a bank of high-quality Magento extensions to enhance your website functionalities comprehensively.</p>
		<?php 
			echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('services-homepage')->toHtml();
		?>
	</div>
</div>