<section class="section introduce margin-top">
	<?php echo $this->getChildHtml('home.main.introduce');?>
</section>
<section class="section our-work margin-top">
	<?php echo $this->getChildHtml('home.main.our.work');?>
</section>
<section class="section middle-block margin-top">
	<?php echo $this->getChildHtml('home.main.middle.block');?>
</section>
<section class="section contact-us margin-top">
	<?php echo $this->getChildHtml('home.main.contact.us');?>
</section>
<section class="section our-client margin-top">
	<?php echo $this->getChildHtml('home.main.our.client');?>
</section>
<section class="section lastest-news margin-top">
	<?php echo $this->getChildHtml('home.main.lastest.news');?>
</section>
<section class="section newsletter margin-top">
	<?php echo $this->getChildHtml('home.main.newsletter');?>
</section>