<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?php //echo $block->getToolbarHtml() ?>
    <?php //echo $block->getAdditionalHtml() ?>
    <?php
    $pos = $block->getPositioned();
    ?>
    <div class="main-container-products wrapper category-product-list">
        <?php $iterator = 1; ?>
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
			<?php
			$product_id = $_product->getId();
			$_product = $objectManager->create('Magento\Catalog\Model\Product')->load($product_id);
			?>
                <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                <div class="product-item-info">                
					<div class="product-header">
						<div class="product-name">
							<a href="<?php echo $_product->getProductUrl();?>"><span><?php echo $_product->getName() . " " . $_product->getResource()->getAttribute('wine_year')->getFrontend()->getValue($_product);?></span></a>
							<!--<div><span><?php echo $_product->getWinehouse();?></span></div> -->
						</div>
					</div>
					<div class="product-content">
						<div class="product-price">
							<div class="product-short-description">
								<span><?php echo $_product->getWineArea();?></span>
							</div>
							<div class="product-weight">
							<!--<span><?php echo $_product->getWineVolume() . " cl.";?></span> -->
							<span>75 cl.</span>

							</div>
							<div class="price-box price-final_price">
								<div class="old-price">
									<span>van</span>
									<span><?php echo number_format((float)$_product->getPrice(), 2, '.', '');?></span>
								</div>
								<div class="special-price">
									<span>voor</span>
									<span class="price"><?php echo number_format((float)$_product->getSpecialPrice(), 2, '.', '');?></span>
								</div>
								<div class="per-bottle">
									<span>per fles</span>
								</div>
							</div>
						</div>
						<div class="product-image">
							<?php
							$productImage = $block->getImage($_product, "category_page_grid");
							
							$_imageHelper = $objectManager->get('Magento\Catalog\Helper\Image');
							$productImage = $_imageHelper->init($_product, 'small_image', ['type'=>'small_image'])->keepAspectRatio(true)->resize('200','320')->getUrl();
							
							?>
							<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo">
								<?php //echo $productImage->toHtml(); ?><img src="<?php echo $productImage; ?>" />
							</a>
						</div>
					</div>
					<?php 
					$ratingOb = $objectManager->create('Magento\Review\Model\Rating')->getEntitySummary($_product->getId());  
					$ratings = 0;
					if ($ratingOb->getCount() != 0)
						$ratings = $ratingOb->getSum()/$ratingOb->getCount();
					?>
					<div class="product-footer">
						<div class="product-reviews-summary product-review">
							<div class="rating-summary">
								<div class="rating-result">
									<span style="width:<?php echo $ratings; ?>%"></span>
								</div>
								<div class="count"><?php echo $ratingOb->getCount() == 0 ? '0 reviews' : $ratingOb->getCount() . ' reviews'; ?></div>
							</div> 
						</div>
						<div class="product-add-to-cart">
							<?php if ($_product->isSaleable()) {?>
							<?php $postParams = $block->getAddToCartPostParams($_product); ?>
							<form data-role="tocart-form" action="<?php echo $postParams['action']; ?>" method="post">
								<input type="hidden" name="product" value="<?php echo $postParams['data']['product']; ?>">
								<input type="hidden" name="<?php echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
								<?php echo $block->getBlockHtml('formkey')?>
								<button type="submit" title="<?php echo 'Bestel'; ?>" class="action tocart primary">
									<div><?php echo 'Bestel'; ?></div>
								</button>
							</form>
							<?php }?>
						</div>
					</div>
				</div>
                <?php echo($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
            <?php endforeach; ?>
        </ol>
    </div>
    <?php //echo $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
