<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php
/** @var \Magento\Catalog\Pricing\Render\PriceBox $block */

/** @var \Magento\Catalog\Pricing\Price\TierPrice $tierPriceModel */
$tierPriceModel = $block->getPrice();
$tierPrices = $tierPriceModel->getTierPriceList();
$msrpShowOnGesture = $block->getPriceType('msrp_price')->isShowPriceOnGesture();
$product = $block->getSaleableItem();

$productId = $product->getId();
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$product_obj = $objectManager->create('Magento\Catalog\Model\Product')->load($productId);
$tier_price = $product_obj->getTierPrice();
$tp = 0;
$difference = 0;
if (count($tier_price) > 0) {
    foreach ($tier_price as $pirces) {
        foreach (array_reverse($pirces) as $k => $v) {
            if ($k == "price") {
                $tp = number_format($v, 2, '.', '');
            }
        }
    }
    $pPrice = number_format($product_obj->getPrice(), 2, '.', '');
    $difference = ($pPrice - $tp);
}
$requestInterface = $objectManager->get('Magento\Framework\App\RequestInterface');
$controllerName = $requestInterface->getControllerName();

$priceHelper = $objectManager->create('Magento\Framework\Pricing\Helper\Data'); // Instance of Pricing Helper
 $formattedPrice = $priceHelper->currency($tp, true, false);

$priceHtml = '<span class="price-container price-tier_price tax weee"><span data-price-type="" class="price-wrapper "><span class="price">'.$formattedPrice.'</span></span></span>';
?>

<?php if (count($tierPrices)) : ?>
    <label class="tier-price-label">Bulk Discount Option:</label>
    <ul class="<?= /* @escapeNotVerified */ ($block->hasListClass() ? $block->getListClass() : 'prices-tier items') ?>">
    <?php foreach ($tierPrices as $index => $price) : ?>
        <li class="item">
            <?php
                $productId = $product->getId();
                $isSaleable = $product->isSaleable();
                $popupId = 'msrp-popup-' . $productId . $block->getRandomString(20);
                if ($msrpShowOnGesture && $price['price']->getValue() < $product->getMsrp()):
                    $addToCartUrl = '';
                    if ($isSaleable) {
                        $addToCartUrl = $this->helper('\Magento\Checkout\Helper\Cart')
                            ->getAddUrl($product, ['qty' => $price['price_qty']]);
                    }
                    $tierPriceData = [
                        'addToCartUrl' => $addToCartUrl,
                        'name' => $product->getName(),
                        'realPrice' => $block->renderAmount(
                            $price['price'],
                            [
                                'price_id'          => $index,
                                'id_suffix'         => '-' . $index,
                                'include_container' => true
                            ]
                        ),
                        'msrpPrice' => $block->renderAmount(
                            $block->getPriceType('msrp_price')->getAmount(),
                            [
                                'price_id'          => $index,
                                'id_suffix'         => '-' . $index,
                                'include_container' => true
                            ]
                        ),
                    ];
                    if ($block->getCanDisplayQty($product)) {
                        $tierPriceData['qty'] = $price['price_qty'];
                    }
                ?>
                <?= /* @escapeNotVerified */ __('Buy %1 for: ', $price['price_qty']) ?>
                <a href="javascript:void(0);"
                   id="<?= /* @escapeNotVerified */ ($popupId) ?>"
                   data-tier-price="<?= $block->escapeHtml($block->jsonEncode($tierPriceData)) ?>">
                    <?= /* @escapeNotVerified */ __('Click for price') ?></a>
                <?php else:
                    $priceAmountBlock = $block->renderAmount(
                        $price['price'],
                        [
                            'price_id'          => $index,
                            'id_suffix'         => '-' . $index,
                            'include_container' => true,
                            'zone' => \Magento\Framework\Pricing\Render::ZONE_ITEM_OPTION
                        ]
                    );
                ?>
                <?php /* @escapeNotVerified */ echo ($block->getShowDetailedPrice() !== false)
                        ? __(
                            'Buy %1pcs :: Price: %2',
                            $price['price_qty'],
                            $priceHtml
                        )
                        : __('Buy %1 for %2 each', $price['price_qty'], $priceAmountBlock);
                ?>
            <?php endif; ?>
        </li>
    <?php endforeach; ?>
    </ul>
    <?php if ($msrpShowOnGesture):?>
        <script type="text/x-magento-init">
            {
                ".product-info-main": {
                    "addToCart": {
                        "origin": "tier",
                        "addToCartButton": "#product_addtocart_form [type=submit]",
                        "inputQty": "#qty",
                        "attr": "[data-tier-price]",
                        "productForm": "#product_addtocart_form",
                        "productId": "<?= /* @escapeNotVerified */ $productId ?>",
                        "productIdInput": "input[type=hidden][name=product]",
                        "isSaleable": "<?= /* @escapeNotVerified */ $isSaleable ?>"
                    }
                }
            }
        </script>
    <?php endif;?>
<?php endif; ?>
