<?php
/**
 * @category FishPig
 * @package FishPig_WordPress
 * @notes This template is used when there post/list.phtml doesn't have a child block called 'renderer'
 * @notes This happens when post/list.phtml is called in via PHP rather than via the default layout handles
 */
?>
<?php if ($post = $this->getPost()): ?>
	<div class="post-list-item">
		<div class="post-entry">
			<?php if ($image = $post->getImage()): ?>
			<a href="<?php echo $post->getUrl() ?>" title="<?php echo $this->escapeHtml($post->getName()) ?>">
				<div class="post-image">
					<img src="<?php echo $image->getMediumImage() ?>" alt="<?php echo $this->escapeHtml($post->getName()) ?>"/>
					<div class="detail">
						<div class="post-name"><p><?php echo $this->escapeHtml($post->getName()) ?></p></div>
						<div class="post-date">
							<p><?php echo $post->getUser()->getDisplayName() ?>, <?php echo $post->getPostDate() ?></p>
						</div>
					</div>
				</div>
			</a>
			<?php endif; ?>
		</div>
	</div>
<?php endif; ?>