<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Top menu for store
 *
 * @var $block \Magento\Theme\Block\Html\Topmenu
 */
?>
<?php $columnsLimit = $block->getColumnsLimit() ?: 0; ?>
<?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit) 

/*<nav class="navigation" data-action="navigation">
    <ul data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
        <?php echo $_menu; ?>
        <?php echo $block->getChildHtml(); ?>
    </ul>
</nav>*/
?>
<nav class="navigation" data-action="navigation">
    <ul data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
		<li class="soort">
			<a href="/soort.html">Soort</a>
			<div class="expand">+</div>
			<ul class="dropdown switcher-dropdown submenu ui-menu ui-widget ui-widget-content ui-corner-all">
				<li class="view-company-element"><a href="#">Redxxx</a></li>
				<li class="view-company-element"><a href="#">White</a></li>
			</ul>
		</li>
		<li><a href="/land.html">Land</a></li>
		<li><a href="/druif.html">Druif</a></li>
		<li><a href="/prijs.html">Prijs</a></li>
		<li><a href="/horeca.html">Horeca</a></li>
	</ul>
</nav>
