<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession     = $objectManager->get( 'Magento\Customer\Model\Session' ); ?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __( 'Add to Cart' ); ?>

<?php if ( $_product->isSaleable() ): ?>
    <div class='quantity_section'>
		<?php if ( $block->shouldRenderQuantity() ): ?>
            <div class="field qty">
                <label class="label text-primary" for="qty"><span><?php /* @escapeNotVerified */
						echo __( 'QUANTITY' ) ?></span></label>
                <div class="control incrementer">


                    <input type="number"
                           name="qty"
                           id="qty"
                           maxlength="12"
                           value="<?php /* @escapeNotVerified */
					       echo $block->getProductDefaultQty() * 1 ?>"
                           title="<?php /* @escapeNotVerified */
					       echo __( 'Qty' ) ?>" class="input-text qty"
                           data-validate="<?php echo $block->escapeHtml( json_encode( $block->getQuantityValidators() ) ) ?>"
                    />


                </div>
            </div>
		<?php endif; ?>
    </div>

    <div class="box-tocart">
        <div class="fieldset">

            <div class="actions">
                <button type="submit"
                        title="<?php /* @escapeNotVerified */
				        echo $buttonTitle ?>"
                        class="action btn btn-primary-transparent  tocart"
                        id="product-addtocart-button">
                    <span><?php /* @escapeNotVerified */
	                    echo $buttonTitle ?></span>
                </button>
				<?php echo $block->getChildHtml( '', true ) ?>
            </div>
        </div>
    </div>
    <div class="box-towishlist">
        <div class="fieldset">
            <div class="actions">
                <a href="javascript:void(0);" class="action btn btn-primary-transparent m-b-30" id="mw-add-wishlist"
                   title="<?php echo $block->escapeHtml( __( 'Add to Wish List' ) ); ?>"
                   aria-label="<?php echo $block->escapeHtml( __( 'Add to Wish List' ) ); ?>"
                   data-action="add-to-wishlist" role="button">
                    <span><?php /* @escapeNotVerified */
	                    echo __( 'Add to Wish List' ) ?></span></a>
				<?php echo $block->getChildHtml( '', true ) ?>
            </div>
        </div>
    </div>
<?php endif; ?>

<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }


</script>

<?php if ( ! $block->isRedirectToCartEnabled() ) : ?>
    <script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "catalogAddToCart": {
                "bindSubmit": true
            }
        }
    }


    </script>
<?php endif; ?>

<script type="text/javascript">
    jQuery(document).ready(function () {
        jQuery("#mw-add-wishlist").on('click', function () {
            var producttype = '<?php echo $_product->getTypeId(); ?>';
            var id = jQuery("input[name='product']").val();
            var key = jQuery("input[name='form_key']").val();
            var product_name = jQuery("input[name='product_name']").val();
            var super_attribute = '';
            var optionscount = 0;
            var selectcount = 0;
            var url = '<?php echo $this->getUrl( 'wishlist' ) ?>index/add?product=' + id + '&form_key=' + key;
            var errorhtml = '';
            jQuery(".mage-error").remove();

            if (producttype == "configurable") {
                jQuery(".swatch-attribute").each(function () {
                    optionscount++;
                    if (jQuery(this).attr('option-selected')) {
                        selectcount++;
                        super_attribute += "&super_attribute[" + jQuery(this).attr('attribute-id') + "]=" + jQuery(this).attr('option-selected');
                    }
                    else {
                        errorhtml = "<div for='super_attribute[" + jQuery(this).attr('attribute-id') + "]' generated='true' class='mage-error' id='super_attribute[" + jQuery(this).attr('attribute-id') + "]-error' >This is a required field.</div>";
                        if (jQuery("#super_attribute[" + jQuery(this).attr('attribute-id') + "]-error").length == 0) {
                            jQuery(this).append(errorhtml);
                            jQuery('.quantity_section').removeClass('size_error');
                            jQuery('.quantity_section').removeClass('color_error');
                            jQuery('div.mage-error:visible').each(function () {
                                var error_elem = jQuery(this).parent().attr('attribute-code');
                                var error_elem_extra = error_elem + '_error';
                                jQuery('.quantity_section').addClass(error_elem_extra);
                            });
                        }

                    }
                });
            }

            if (producttype == "configurable" && super_attribute != "" && optionscount == selectcount) {
                url = url + super_attribute;
                addtoWishlist(url, product_name);
            }
            if (producttype != "configurable") {
                addtoWishlist(url, product_name);
            }

        });

    });

    function addtoWishlist(url, product_name) {
        jQuery.ajax({
            dataType: 'html',
            type: 'POST',
            //url:'<?php echo $this->getUrl( 'wishlist' ) ?>index/add/product/'+id+'/form_key/'+key,
            url: url,
            success: function (result) {
				<?php if($customerSession->isLoggedIn()){ ?>
                jQuery(".page .container").remove();
                jQuery(".page").append("<div class='container'><span class='mw_suc-msg'><span class='mw-cart-product-name'>" + product_name + "</span> has been added to your Wish List.</span></div>");
				<?php } else { ?>
                location.href = "<?php echo $this->getUrl( 'customer/account/login' ) ?>";
				<?php }?>


            }
        });
    }

    //<![CDATA[
    //  jQuery(document).ready(function(){
    //    jQuery('.increment_qty').click(function() {
    //      var oldVal = jQuery(this).parent().find("input").val();
    //      if ( parseFloat(oldVal) >= 1 ) {
    //        var newVal = parseFloat(oldVal) + 1;
    //        jQuery(this).parent().find("input").val(newVal);
    //      }
    //    });
    //
    //    jQuery('.decrement_qty').click(function() {
    //      var oldVal = jQuery(this).parent().find("input").val();
    //      if ( parseFloat(oldVal) >= 2 ) {
    //        var newVal = parseFloat(oldVal) - 1;
    //        jQuery(this).parent().find("input").val(newVal);
    //      }
    //    });
    //  });
    //]]>
</script>